<?php
session_start();
require_once '../../src/templates/admin_header.php';
require_once '../../src/includes/db_connect.php';
if ($_SESSION['role'] !== 'admin' && $_SESSION['role'] !== 'staff') { exit('Access Denied'); }
?>

<!-- =================================================================== -->
<!--                  NEW CSS FOR MODAL AND CARD                         -->
<!-- =================================================================== -->
<style>
    /* Table Styles */
    table { width: 100%; border-collapse: collapse; }
    th, td { border-bottom: 1px solid var(--border-color); padding: 12px; text-align: left; vertical-align: middle; font-size: 14px; }
    th { font-weight: 600; color: var(--text-muted); }
    .status-available { color: #27ae60; font-weight: bold; }
    .status-used { color: #e74c3c; font-weight: bold; }
    .action-link { text-decoration: none; color: #3498db; margin-right: 10px; cursor: pointer; }

    /* Modal Styles */
    .modal {
        display: none; position: fixed; z-index: 1000; left: 0; top: 0;
        width: 100%; height: 100%; overflow: auto; background-color: rgba(0,0,0,0.5);
        align-items: center; justify-content: center;
    }
    .modal-content {
        position: relative; background-color: #fefefe; margin: auto;
        padding: 0; border: 1px solid #888; width: 80%; max-width: 500px;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2); border-radius: 10px; overflow: hidden;
    }
    .modal-header { padding: 15px 20px; background-color: var(--primary-color); color: white; }
    .modal-header h2 { margin: 0; font-size: 18px; }
    .modal-body { padding: 20px; }
    .modal-footer { padding: 15px 20px; background-color: #f9f9f9; text-align: right; border-top: 1px solid #eee; }
    .close-btn { color: white; float: right; font-size: 28px; font-weight: bold; cursor: pointer; }

    /* Activation Card Styles (inside modal) */
    .activation-card { text-align: center; }
    .activation-card h3 { font-size: 20px; margin-bottom: 20px; }
    .activation-card img { width: 200px; height: 200px; margin-bottom: 20px; }
    .card-details p { margin: 8px 0; text-align: left; border-bottom: 1px solid #eee; padding-bottom: 8px; }
    .card-details p strong { color: #333; min-width: 140px; display: inline-block; }
</style>

<div class="content-header"><h2>Activation Code Management</h2></div>

<div class="card">
    <?php if (isset($_SESSION['message'])) { /* ... message display ... */ } ?>
    <table>
        <thead>
            <tr>
                <th>Code</th><th>Package</th><th>Status</th><th>Generated By</th><th>Used By</th><th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $sql = "SELECT ac.*, p.name AS package_name, gen_user.name AS generator_name, used_user.name AS used_by_name FROM activation_codes ac JOIN packages p ON ac.package_id = p.id JOIN users gen_user ON ac.generated_by_id = gen_user.id LEFT JOIN users used_user ON ac.used_by_id = used_user.id ORDER BY ac.id DESC";
            $result = $mysqli->query($sql);

            if ($result && $result->num_rows > 0) {
                while ($code = $result->fetch_assoc()) {
                    $status_class = $code['status'] === 'available' ? 'status-available' : 'status-used';
                    echo "<tr>";
                    echo "<td><strong>" . htmlspecialchars($code['code']) . "</strong></td>";
                    echo "<td>" . htmlspecialchars($code['package_name']) . "</td>";
                    echo "<td><span class='" . $status_class . "'>" . ucfirst($code['status']) . "</span></td>";
                    echo "<td>" . htmlspecialchars($code['generator_name']) . "</td>";
                    echo "<td>" . ($code['used_by_name'] ? htmlspecialchars($code['used_by_name']) : 'N/A') . "</td>";
                    echo '<td>';
                    // --- UPDATED ACTIONS ---
                    echo '<a class="action-link view-details-btn" data-id="'.$code['id'].'">View</a>';
                    if ($code['status'] === 'available') {
                        echo '<a href="download_card.php?id='.$code['id'].'" class="action-link">Download</a>';
                        if ($_SESSION['role'] === 'admin') {
                            // ... (your existing delete form)
                        }
                    }
                    echo '</td>';
                    echo "</tr>";
                }
            } else { /* ... no codes found message ... */ }
            ?>
        </tbody>
    </table>
</div>

<!-- =================================================================== -->
<!--                        THE MODAL STRUCTURE                          -->
<!-- =================================================================== -->
<div id="detailsModal" class="modal">
    <div class="modal-content">
        <div class="modal-header">
            <span class="close-btn">&times;</span>
            <h2>Activation Card Details</h2>
        </div>
        <div class="modal-body" id="modal-body-content">
            <!-- Content will be loaded here by JavaScript -->
            <p>Loading details...</p>
        </div>
        <div class="modal-footer">
            <button id="modal-download-btn" class="btn btn-primary">Download Card</button>
        </div>
    </div>
</div>

<!-- =================================================================== -->
<!--                   JAVASCRIPT FOR MODAL & AJAX                       -->
<!-- =================================================================== -->
<script>
document.addEventListener('DOMContentLoaded', function() {
    const modal = document.getElementById('detailsModal');
    const modalBody = document.getElementById('modal-body-content');
    const modalDownloadBtn = document.getElementById('modal-download-btn');
    const closeBtn = document.querySelector('.close-btn');

    document.querySelectorAll('.view-details-btn').forEach(button => {
        button.addEventListener('click', function() {
            const codeId = this.dataset.id;
            modal.style.display = 'flex'; // Show modal
            modalBody.innerHTML = '<p>Loading details...</p>';
            modalDownloadBtn.onclick = () => { window.location.href = `download_card.php?id=${codeId}`; };
            
            // Use fetch to get the card content from a new API
            fetch(`api_get_card_details.php?id=${codeId}`)
                .then(response => response.json())
                .then(data => {
                    if (data.error) {
                        modalBody.innerHTML = `<p style="color:red;">${data.error}</p>`;
                    } else {
                        const cardHtml = `
                            <div class="activation-card">
                                <h3>Activation Card</h3>
                                <img src="qr_generator.php?data=${encodeURIComponent(data.code)}" alt="QR Code">
                                <div class="card-details">
                                    <p><strong>Activation Code:</strong> ${data.code}</p>
                                    <p><strong>Package:</strong> ${data.package_name}</p>
                                    <p><strong>Generated By:</strong> ${data.generator_name}</p>
                                    <p><strong>Date Generated:</strong> ${data.created_at}</p>
                                    <p><strong>Status:</strong> ${data.status}</p>
                                </div>
                            </div>
                        `;
                        modalBody.innerHTML = cardHtml;
                    }
                });
        });
    });
    
    closeBtn.onclick = () => { modal.style.display = 'none'; };
    window.onclick = (event) => {
        if (event.target == modal) {
            modal.style.display = 'none';
        }
    };
});
</script>

<?php require_once '../../src/templates/admin_footer.php'; $mysqli->close(); ?>