<?php
session_start();
require_once '../../src/includes/db_connect.php';
// This page is for download, so it should not include the admin template
if ($_SESSION['role'] !== 'admin' && $_SESSION['role'] !== 'staff') { die('Access Denied'); }

$code_id = isset($_GET['id']) ? (int)$_GET['id'] : 0;
if ($code_id <= 0) { die("Invalid ID."); }

// Fetch the same data as the API
$sql = "SELECT ac.code, ac.status, ac.created_at, p.name as package_name, u.name as generator_name FROM activation_codes ac JOIN packages p ON ac.package_id = p.id JOIN users u ON ac.generated_by_id = u.id WHERE ac.id = ?";
$stmt = $mysqli->prepare($sql);
$stmt->bind_param("i", $code_id);
$stmt->execute();
$data = $stmt->get_result()->fetch_assoc();
if (!$data) { die("Code not found."); }
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Activation Card - <?php echo htmlspecialchars($data['code']); ?></title>
    <style>
        body { font-family: Arial, sans-serif; }
        .activation-card {
            width: 500px; padding: 20px; border: 2px solid #333; margin: 20px auto;
            text-align: center; border-radius: 10px; background-color: #f9f9f9;
        }
        h3 { font-size: 24px; margin-bottom: 20px; border-bottom: 1px solid #ccc; padding-bottom: 10px; }
        img { width: 250px; height: 250px; margin-bottom: 20px; }
        .card-details { text-align: left; }
        .card-details p { margin: 10px 0; font-size: 16px; }
        .card-details p strong { color: #000; min-width: 150px; display: inline-block; }
    </style>
</head>
<body onload="window.print()"> <!-- Optional: Trigger print dialog on load -->
    <div class="activation-card">
        <h3>Activation Card</h3>
        <img src="qr_generator.php?data=<?php echo urlencode($data['code']); ?>" alt="QR Code">
        <div class="card-details">
            <p><strong>Activation Code:</strong> <?php echo htmlspecialchars($data['code']); ?></p>
            <p><strong>Package:</strong> <?php echo htmlspecialchars($data['package_name']); ?></p>
            <p><strong>Generated By:</strong> <?php echo htmlspecialchars($data['generator_name']); ?></p>
            <p><strong>Date Generated:</strong> <?php echo date('m/d/Y', strtotime($data['created_at'])); ?></p>
            <p><strong>Status:</strong> <?php echo ucfirst($data['status']); ?></p>
        </div>
    </div>
</body>
</html>