<?php
session_start();
require_once '../../src/includes/db_connect.php';

// Security check: Admins only, POST request
if ($_SESSION['role'] !== 'admin' || $_SERVER['REQUEST_METHOD'] !== 'POST') {
    header('Location: member_management.php');
    exit();
}

$member_id_to_delete = isset($_POST['id']) ? (int)$_POST['id'] : 0;

if ($member_id_to_delete <= 0) {
    $_SESSION['message'] = "Invalid Member ID provided.";
    $_SESSION['msg_type'] = "danger";
    header('Location: member_management.php');
    exit();
}

// --- START TRANSACTION ---
$mysqli->begin_transaction();
try {
    // --- SAFETY CHECK: Prevent deleting a member who has a downline ---
    $stmt_check = $mysqli->prepare("SELECT id FROM genealogy_tree WHERE upline_id = ?");
    $stmt_check->bind_param("i", $member_id_to_delete);
    $stmt_check->execute();
    if ($stmt_check->get_result()->num_rows > 0) {
        throw new Exception("Cannot delete this member because they have a downline. Please move their downline members first.");
    }
    $stmt_check->close();
    
    // --- 1. Claw back (delete) all UNPROCESSED points that this member generated ---
    $stmt_delete_points = $mysqli->prepare("DELETE FROM binary_points WHERE source_user_id = ? AND status = 'unprocessed'");
    $stmt_delete_points->bind_param("i", $member_id_to_delete);
    $stmt_delete_points->execute();
    $points_clawed_back = $stmt_delete_points->affected_rows; // Get how many point entries were removed
    $stmt_delete_points->close();

    // --- 2. Delete the member from all related tables using their ID ---
    // The order is important to respect foreign key constraints if they existed.
    
    // a. Delete from genealogy_tree
    $stmt_tree = $mysqli->prepare("DELETE FROM genealogy_tree WHERE user_id = ?");
    $stmt_tree->bind_param("i", $member_id_to_delete);
    $stmt_tree->execute();
    $stmt_tree->close();
    
    // b. Delete from member_profiles (and any other related tables like wallets, commissions, etc.)
    $stmt_profile = $mysqli->prepare("DELETE FROM member_profiles WHERE user_id = ?");
    $stmt_profile->bind_param("i", $member_id_to_delete);
    $stmt_profile->execute();
    $stmt_profile->close();
    
    $stmt_wallet = $mysqli->prepare("DELETE FROM wallets WHERE user_id = ?");
    $stmt_wallet->bind_param("i", $member_id_to_delete);
    $stmt_wallet->execute();
    $stmt_wallet->close();

    // ... add DELETE statements for commissions, encashment_requests, etc. if you want a full wipe ...
    
    // c. Finally, delete the main user record
    $stmt_user = $mysqli->prepare("DELETE FROM users WHERE id = ? AND role = 'member'");
    $stmt_user->bind_param("i", $member_id_to_delete);
    $stmt_user->execute();
    $user_deleted_count = $stmt_user->affected_rows;
    $stmt_user->close();
    
    if ($user_deleted_count === 0) {
        throw new Exception("Member could not be found or was not a member-role user.");
    }

    // If we reach here, all deletions were successful
    $mysqli->commit();
    $_SESSION['message'] = "Member (ID: $member_id_to_delete) has been permanently deleted. Unprocessed points generated by them ($points_clawed_back records) have been clawed back.";
    $_SESSION['msg_type'] = "success";

} catch (Exception $e) {
    $mysqli->rollback();
    $_SESSION['message'] = "Error: Could not delete member. " . $e->getMessage();
    $_SESSION['msg_type'] = "danger";
}

$mysqli->close();
header('Location: member_management.php');
exit();